wandb_version: 1

data_path:
  desc: null
  value: dataset/full_dataset.csv
test_size:
  desc: null
  value: 0.2
targets:
  desc: null
  value:
  - rnti_count
  - rb_down
  - rb_up
  - down
  - up
num_lags:
  desc: null
  value: 10
identifier:
  desc: null
  value: District
nan_constant:
  desc: null
  value: 0
x_scaler:
  desc: null
  value: minmax
y_scaler:
  desc: null
  value: minmax
outlier_detection:
  desc: null
  value: true
criterion:
  desc: null
  value: mse
fl_rounds:
  desc: null
  value: 20
fraction:
  desc: null
  value: 1.0
aggregation:
  desc: null
  value: fedavg
epochs:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: adam
batch_size:
  desc: null
  value: 128
local_early_stopping:
  desc: null
  value: false
local_patience:
  desc: null
  value: 50
max_grad_norm:
  desc: null
  value: 0.0
reg1:
  desc: null
  value: 0.0
reg2:
  desc: null
  value: 0.0
model_name:
  desc: null
  value: rnn
num_subset:
  desc: null
  value: 5
device:
  desc: null
  value: cuda
instance:
  desc: null
  value: baseline-fedavg
cuda:
  desc: null
  value: true
seed:
  desc: null
  value: 0
assign_stats:
  desc: null
  value: null
use_time_features:
  desc: null
  value: false
outlier_columns:
  desc: null
  value:
  - rb_down
  - rb_up
  - down
  - up
outlier_kwargs:
  desc: null
  value:
    ElBorn:
    - 10
    - 90
    LesCorts:
    - 10
    - 90
    PobleSec:
    - 5
    - 95
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707803178.490456
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
